# Service de tipo LoadBalancer para WordPress.
# Azure provisiona automáticamente un balanceador con IP pública, exponiendo la aplicación a Internet.

apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress # Enruta a los pods de WordPress
  ports:
    - port: 80 # Puerto público
      targetPort: 80 # Puerto del contenedor