server {
    listen 443 ssl;
    server-name cp2.unir.local;

    # Certificado y clave (se generan durante el build de la imagen)
    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    # Autenticación básica: pide usuario/contraseña en toda la web
    auth_basic           "Area restringida - CP2 UNIR";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}