# Bloque 'server': define un servidor virtual de Nginx.
server {
    listen 443 ssl; # Escucha en el puerto 443 (HTTPS) con TLS activado
    server_name cp2.unir.local; # Nombre de dominio que atiende este servidor

    # Certificado y clave (se generan durante el build de la imagen)
    ssl_certificate     /etc/nginx/certs/server.crt; # Certificado público x.509
    ssl_certificate_key /etc/nginx/certs/server.key; # Clave privada asociada

    # Autenticación básica: pide usuario/contraseña en toda la web
    auth_basic           "Area restringida - CP2 UNIR"; # Mensaje del diálogo de login
    auth_basic_user_file /etc/nginx/.htpasswd; # Fichero de credenciales (creado con htpasswd)

    # Contenido servido:
    location / { # Aplica a todas las rutas ("/")
        root /usr/share/nginx/html; # Carpeta donde están los ficheros web
        index index.html; # Fichero que se sirve por defecto
    }
}